export const pokemons = [
  {
    id: 1,
    name: 'Bulbasaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon1.jpg'),
  },
  {
    id: 2,
    name: 'Ivysaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon2.jpg'),
  },
  {
    id: 3,
    name: 'Venusaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon3.jpg'),
  },
  {
    id: 4,
    name: 'Bulbasaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon1.jpg'),
  },
  {
    id: 5,
    name: 'Ivysaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon2.jpg'),
  },
  {
    id: 6,
    name: 'Venusaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon3.jpg'),
  },
  {
    id: 7,
    name: 'Bulbasaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon1.jpg'),
  },
  {
    id: 8,
    name: 'Ivysaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon2.jpg'),
  },
  {
    id: 9,
    name: 'Venusaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon3.jpg'),
  },
  {
    id: 10,
    name: 'Bulbasaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon1.jpg'),
  },
  {
    id: 11,
    name: 'Ivysaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon2.jpg'),
  },
  {
    id: 12,
    name: 'Venusaur',
    type: 'Grass/Poison',
    abilities: ['Overgrow', 'Chlorophyll'],
    image: require('../../assets/PokemonImages/pokemon3.jpg'),
  },
];
