export const gamesData = [
  {
    id: 1,
    name: 'The Legend of Zelda: Breath of the Wild',
    platform: 'Nintendo Switch',
    genre: 'Action-Adventure',
    releaseYear: 2017,
    rating: 9.8,
    imageUrl: require('../../assets/games/zelda.jpg'),
  },

  {
    id: 2,
    name: 'God of War',
    platform: 'PlayStation 4',
    genre: 'Action',
    releaseYear: 2018,
    rating: 9.6,
    imageUrl: require('../../assets/games/god-of-war.jpg'),
  },
  {
    id: 3,
    name: 'Red Dead Redemption 2',
    platform: 'PlayStation 4, Xbox One, PC',
    genre: 'Action-Adventure',
    releaseYear: 2018,
    rating: 9.7,
    imageUrl: require('../../assets/games/rdr2.jpg'),
  },
  {
    id: 4,
    name: 'Minecraft',
    platform: 'PC, PlayStation, Xbox, Switch',
    genre: 'Sandbox',
    releaseYear: 2011,
    rating: 9.5,
    imageUrl: require('../../assets/games/minecraft.jpg'),
  },
  {
    id: 5,
    name: 'Fortnite',
    platform: 'PC, PlayStation, Xbox, Switch',
    genre: 'Battle Royale',
    releaseYear: 2017,
    rating: 8.5,
    imageUrl: require('../../assets/games/fortnight.jpg'),
  },
  {
    id: 6,
    name: 'Cyberpunk 2077',
    platform: 'PC, PlayStation, Xbox',
    genre: 'RPG',
    releaseYear: 2020,
    rating: 7.5,
    imageUrl: require('../../assets/games/cyberbunk.jpg'),
  },
  {
    id: 7,
    name: 'Super Mario Odyssey',
    platform: 'Nintendo Switch',
    genre: 'Platformer',
    releaseYear: 2017,
    rating: 9.7,
    imageUrl: require('../../assets/games/super-mario.jpg'),
  },
  {
    id: 8,
    name: 'The Witcher 3: Wild Hunt',
    platform: 'PC, PlayStation, Xbox, Switch',
    genre: 'RPG',
    releaseYear: 2015,
    rating: 9.9,
    imageUrl: require('../../assets/games/withcer-3.jpg'),
  },
  {
    id: 9,
    name: 'Apex Legends',
    platform: 'PC, PlayStation, Xbox, Switch',
    genre: 'Battle Royale',
    releaseYear: 2019,
    rating: 8.9,
    imageUrl: require('../../assets/games/apex-legends.jpg'),
  },
  {
    id: 10,
    name: 'Among Us',
    platform: 'PC, Mobile',
    genre: 'Party',
    releaseYear: 2018,
    rating: 8.1,
    imageUrl: require('../../assets/games/among-us.jpg'),
  },
];
